network_config:
  num_convolutional_layers: 7
  num_filters: 128
  kernel_size: [3, 3]
  pool_size: [2, 2]
  dense_layer_size: 128
  dropout_rate: 0.0
  batch_normalization: True
  small_first: False
training_config:
  data_path: 'gs://bird-classifier-cnn/processed_images_split.tar.gz'
  categories_path: 'gs://bird-classifier-cnn/cat.txt'
  model_base_name: 'basic_cnn'
  bucket_path: 'gs://bird-classifier-cnn/saved_models'
  input_shape: [256, 256, 3]
  batch_size: 64
  validation_percent: 0.2
  epochs: 60
  num_per_epoch: 12000
  learning_rate: 0.001
  augmented: True
  is_split: True
